const ScheduleBounds = require('./ScheduleBounds');

class ArtifactManuals {
  static ARTIFACT = [
    'ARTIFACT TOOL:',
    '- create_artifact: Render a self-contained artifact in the chat\'s side',
    '  panel for the user to see. Params:',
    '  { "tool": "create_artifact", "params": { "title": "short title",',
    '    "type": "code" | "html" | "svg" | "markdown",',
    '    "language": "(REQUIRED when type=code, e.g. csharp, python, rust)",',
    '    "content": "the COMPLETE content as one string" } }',
    '',
    '  HOW TO PICK `type`: read this carefully, it is the #1 thing that',
    '  goes wrong:',
    '',
    '  • type: "code", DEFAULT for ANY request that names a programming',
    '    language ("write me a Python script", "give me a C# fizzbuzz",',
    '    "a TypeScript helper that…"). Renders in a VS Code-style Monaco',
    '    editor with real syntax highlighting. Just put the SOURCE: no',
    '    HTML wrapper, no <style>, no fake "terminal" UI, no embedded copy',
    '    button. `language` is the language id (csharp, javascript, python,',
    '    rust, go, etc.). DO NOT wrap a code request in an HTML page; the',
    '    Monaco view already handles presentation and is the strictly',
    '    better experience for reading code.',
    '',
    '  • type: "html", ONLY when the user explicitly asks for a webpage,',
    '    a UI mockup, a data visualization, an interactive demo, a',
    '    dashboard, a slide deck, a landing page, etc.: something that is',
    '    meant to BE rendered, not READ as source. Provide a full',
    '    standalone document (inline CSS/JS, no external build step). The',
    '    side panel shows source + live preview split. Asking for HTML',
    '    code itself? Still use type: "html" (the editor + preview split',
    '    is exactly what they want to see).',
    '',
    '  • type: "svg", when the user asks for a vector graphic, icon,',
    '    diagram, or chart that should render as an image. Content is the',
    '    full <svg> element.',
    '',
    '  • type: "markdown", long-form prose: a README, a design doc, a',
    '    spec, a recipe, a list of notes. The panel renders it formatted.',
    '',
    '  After it succeeds, briefly tell the user the artifact opened in the',
    '  side panel; do NOT paste the whole content back to them.',
    '',
    '- edit_artifact: Revise an HTML / SVG / Markdown / Code artifact you',
    '  created earlier in this conversation. Use this (NOT a fresh',
    '  create_artifact) whenever the user says "update it", "change',
    '  that to…", "now make it…", "tweak the styling", etc. AND there is',
    '  a matching artifact in the catalog at the top of this prompt.',
    '',
    '  EDITING A LIVE (interactive) MODULE (type "live" in the catalog): do NOT',
    '  use the content/replacements text modes below. Instead pass the new "html"',
    '  and/or "js" fields (omit a field to keep it), e.g.',
    '  { "tool": "edit_artifact", "params": { "artifactId": "art_…",',
    '    "js": "the complete new module script" } }. (Targeted "replacements" also',
    '  work for live modules; they apply to whichever of html/js the find matches.)',
    '',
    '  TWO MODES (for code/html/svg/markdown artifacts). Prefer #1: it\'s shorter, more reliable, and tolerates',
    '  long files that would otherwise blow your token budget:',
    '',
    '  1. TARGETED REPLACEMENTS (PREFERRED for small edits):',
    '     { "tool": "edit_artifact", "params": {',
    '       "artifactId": "art_…",',
    '       "replacements": [',
    '         { "find": "<title>Hello World</title>",',
    '           "replace": "<title>Lorem Ipsum</title>" },',
    '         { "find": "    <h1>Hello World</h1>",',
    '           "replace": "    <h1>Lorem Ipsum</h1>\\n    <p>…</p>" }',
    '       ]',
    '     } }',
    '     RULES for each replacement:',
    '       • `find` must be an EXACT substring of the CURRENT source:',
    '         exact punctuation, casing, and inner whitespace (e.g.',
    '         "Hello, World!" is NOT "Hello World"). You are editing from',
    '         memory of what you wrote, so keep `find` SHORT and distinctive',
    '         (one phrase or one line), which is less likely to be misremembered',
    '         than a long block with attributes/indentation.',
    '       • If a replacement fails to match, the error returns the artifact\'s',
    '         CURRENT content; copy an exact `find` from THAT and retry. Do NOT',
    '         fall back to a full `content` rewrite for a small change: a rewrite',
    '         regenerates the whole document from memory and silently loses the',
    '         existing design (colors, layout, animations).',
    '       • `find` must match EXACTLY ONCE in the (current) source;',
    '         include surrounding lines as context when a short string',
    '         would match multiple places. To replace every occurrence',
    '         instead, set `"replaceAll": true` on that entry.',
    '       • Replacements apply IN ORDER: replacement N+1 runs against',
    '         the result of N. Plan accordingly when one edit unblocks',
    '         the context for the next.',
    '       • To insert new content next to an anchor: set `find` to a',
    '         small unique anchor line and `replace` to that same anchor',
    '         PLUS your insertion (above or below).',
    '       • To delete a region: set `replace` to "".',
    '',
    '  2. FULL REWRITE (use only when you\'re changing >50% of the file or',
    '     restructuring globally: a list of replacements would be longer',
    '     than the file itself):',
    '     { "tool": "edit_artifact", "params": {',
    '       "artifactId": "art_…",',
    '       "content": "the COMPLETE revised document (NOT a diff, NOT a',
    '         snippet), every line the final artifact should contain"',
    '     } }',
    '',
    '  `type` and `language` are inherited from the source; you cannot',
    '  change a code artifact into an html one via edit (call',
    '  create_artifact for that). `title` is optional and falls back to',
    '  the source title. `edit_artifact` is the text-side counterpart to',
    '  `edit_image`.',
  ].join('\n');

  static LIVE_ARTIFACT = [
    'LIVE ARTIFACT TOOL:',
    '- create_live_artifact: Render an INTERACTIVE module INLINE in the chat (NOT',
    '  the side panel): a live widget the user can actually use. Reactive via',
    '  ResonantJS; Chart.js available on request. Use it for calculators, unit',
    '  converters, toggles/sliders, live charts, small simulations, and live',
    '  lookups that pull real data from websites/APIs (via `luma`, below):',
    '  anything the user interacts with. (For static code to READ, use',
    '  create_artifact instead.)',
    '  { "tool": "create_live_artifact", "params": {',
    '    "title": "short title",',
    '    "html": "the module markup",',
    '    "js": "the module script",',
    '    "libs": ["chartjs"]   // OPTIONAL, only when you need Chart.js',
    '  } }',
    '',
    '  HOW IT RUNS (follow this contract exactly):',
    '  • Your `html` is injected into a container element. Your `js` then runs with',
    '    three things in scope: `root` (that container element), `R` (a ResonantJS',
    '    instance scoped to THIS module), and `Chart` (the Chart.js constructor, but',
    '    only if you listed "chartjs" in libs; otherwise undefined).',
    '    These three are ALREADY defined for you; use them directly. NEVER declare',
    '    them (no `let R`, `var R`, `const root = …`, etc.): redeclaring an injected',
    '    name throws "Identifier \'R\' has already been declared" and the module',
    '    won\'t run. If you don\'t need R at all, simply don\'t reference it.',
    '  • REACTIVE TEXT (use R for SIMPLE values): put res="name" on an element,',
    '    then in js call R.add("name", initialValue). Updating R.name (e.g.',
    '    R.name = R.name + 1) re-renders every element bound to it; no manual DOM',
    '    text update needed. Great for a counter, a total, a status label, a count.',
    '  • DYNAMIC LISTS (build them imperatively; this is expected, NOT a failure to',
    '    "use R"): for a list whose items are added/removed/reordered, keep a plain',
    '    JS array and a render() that rebuilds the rows (document.createElement or',
    '    innerHTML into a root.querySelector(...) container), and call render() on',
    '    each change. R\'s res= bindings are for scalar text, not list re-rendering,',
    '    so mixing "R for the counter, imperative for the list" is the right design.',
    '  • INTERACTION: wire events imperatively in js:',
    '    root.querySelector(".btn").addEventListener("click", () => { R.count = R.count + 1; });',
    '  • FINDING NODES: `root` is the container ELEMENT, not the document. Find',
    '    nodes with root.querySelector("#id") or root.querySelector(".cls") (and',
    '    root.querySelectorAll(...) for many). DO NOT call root.getElementById(...):',
    '    getElementById is a DOCUMENT-only method, so on an element it throws',
    '    "root.getElementById is not a function". Scope every lookup to `root`',
    '    (never the global document) so multiple modules don\'t clash. (Using',
    '    document.createElement(...) to BUILD new nodes is fine; that\'s not a lookup.)',
    '  • THEME: the module renders on a LIGHT (white) card. Style for a light',
    '    theme: dark text on light/pale backgrounds (the normal web default). Do',
    '    NOT assume a dark background or use near-white text.',
    '  • STYLING: LEAN ON THE BUILT-IN HOUSE STYLE; keep your CSS tiny. The host',
    '    already styles PLAIN elements nicely on the light card: <h2>/<h3>, <p>,',
    '    <input>, <select>, <textarea>, <button>, <ul>/<li>, <hr>. So write plain',
    '    markup and it looks good with NO <style> block. For the common patterns use',
    '    these utility classes (already styled; do not redefine them):',
    '      .lm-row (flex row, centered, gap)   .lm-between (row, space-between)',
    '      .lm-grow (flex:1)                    .lm-muted (small grey text)',
    '      .lm-item (a list row w/ divider)     .lm-card (white bordered card)',
    '      .lm-primary (filled accent button)   .lm-ghost (borderless button)',
    '    Only add a SMALL <style> for genuinely custom needs (a specific color, an',
    '    animation). Do NOT ship a large stylesheet re-implementing buttons/inputs/',
    '    layout from scratch: that is wasted output; the house style covers it.',
    '  • CHARTS: put a <canvas> in html, list "chartjs" in libs, then in js:',
    '    new Chart(root.querySelector("canvas"), { type:"bar", data:{…}, options:{…} });',
    '    Give the chart a fixed height so it shows: wrap the canvas in a div with',
    '    an explicit height, e.g. <div style="height:320px"><canvas></canvas></div>,',
    '    and keep maintainAspectRatio:false. (A responsive chart with no sized',
    '    container collapses to zero height.)',
    '  • SELF-CONTAINED CODE: no external <script>/<link> tags, no imports. A',
    '    direct fetch()/XHR to another site fails (CORS) and window.open does',
    '    not work; for web data and tabs use `luma` (below). Use only `R`,',
    '    `root`, (when requested) `Chart`, `store`, and `luma`.',
    '  • PERSISTENT DATA (`store`): a fourth injected value that saves this',
    '    module\'s data so it survives app restarts AND later edits of the module.',
    '    Async API (all return Promises): await store.get("k"), await store.all()',
    '    (the whole saved object), store.set("k", value), store.remove("k"),',
    '    store.onChange(cb) (cb runs with { keys, data } when the data changes',
    '    outside this module; re-render from it). Values must be JSON (numbers,',
    '    strings, booleans, arrays, plain objects). Like root/R/Chart it is',
    '    ALREADY defined; NEVER declare your own `store` variable.',
    '    USE IT whenever the user\'s widget tracks anything worth keeping (tasks,',
    '    scores, entries, settings): load saved state FIRST, then save on every',
    '    change. Top-level await is fine. Pattern:',
    '    "js": "let items = (await store.get(\'items\')) || [];',
    '           function save(){ store.set(\'items\', items); }',
    '           /* call save() in every add/remove/toggle handler, then render */"',
    '    Skip it for stateless widgets (a calculator, a unit converter).',
    '  • LIVE WEB DATA (`luma`): a fifth injected value that reaches through the',
    '    app\'s REAL browser: the widget\'s way to pull live data from any',
    '    website or JSON API (no CORS limits; pages render with JavaScript and',
    '    the app\'s cookies, and bot-blocks that stop plain fetches are handled).',
    '    Async API (both THROW on failure; wrap in try/catch and show the error',
    '    in the widget):',
    '    • await luma.fetchPage(url, { mode: "markdown" }) → the page\'s content',
    '      as a string. mode "markdown" (default: clean readable page text),',
    '      "text" (rendered innerText), or "html" (raw HTML for scraping',
    '      attributes/prices). A JSON API endpoint comes back verbatim whatever',
    '      the mode; JSON.parse the result. Content is capped (~60k chars;',
    '      pass { maxChars } up to 200k if you must parse deep pages).',
    '    • await luma.openTab(url) → opens the page in a real browser tab for',
    '      the user; use this for "view on site" buttons (window.open does NOT',
    '      work inside a module).',
    '    Like root/R/Chart/store it is ALREADY defined; NEVER declare your own',
    '    `luma`. It is null on shared/remote views, so when a widget could be',
    '    shared, feature-detect with `if (luma)` and degrade gracefully.',
    '    USE IT for widgets the user wants fed by a website: price lookups,',
    '    status boards, feeds, search dashboards. Fetch on demand (button click /',
    '    first load), parse, render, and cache results in `store` so the widget',
    '    still shows the last data instantly.',
    '    VERIFY THE URL BEFORE BUILDING: never invent a site\'s URL pattern',
    '    (/isbn/…, /product/…, ?q=…): a guessed path just fails as "HTTP 404"',
    '    inside the widget. FIRST discover the real pattern with the browser',
    '    tools (navigate to the site, perform one search, read the resulting',
    '    tab URL) or web_search, and fetch that exact URL once yourself',
    '    (get_source) to see the REAL content before writing parse logic',
    '    against it. Only then hardcode the pattern into the widget. Pattern:',
    '    "js": "async function refresh(isbn){ R.status = \'loading…\';',
    '           try { const md = await luma.fetchPage(\'https://site.com/Search?id=\' + encodeURIComponent(isbn));',
    '                 const m = md.match(/\\\\$([0-9][0-9.,]*)/); R.price = m ? (\'$\' + m[1]) : \'not found\';',
    '                 store.set(\'last_\' + isbn, R.price); } ',
    '           catch (e) { R.price = \'error: \' + e.message; }',
    '           R.status = \'\'; }"',
    '  • EXTENSION APIs (`luma.ext`): `luma.ext(extensionId)` gives',
    '    `{ call(method, ...args), onEvent(cb) }` onto an extension that publishes',
    '    a Dashboard API. The Hub (id "personal-hub") publishes the user\'s unified',
    '    task board, calendar agenda and conversation queue:',
    '      const hub = luma.ext("personal-hub");',
    '      const tasks = await hub.call("listTasks", {});',
    '      hub.onEvent(({ type }) => { if (type === "task.changed") render(); });',
    '    Methods: listTasks({columnKey?}), getTask(id), createTask({title,',
    '    description?, columnKey?}), moveTask(id, columnKey, {}),',
    '    addTaskMessage(id, body, {}), listColumns(), listEvents({days}),',
    '    listThreads({state:"open"}), setThreadState(id, state, {}). call()',
    '    THROWS when the extension is inactive or the method is not published;',
    '    on surfaces without the bridge `luma` is null and `luma.ext` throws, so',
    '    feature-detect (`if (luma)`, try/catch) and degrade gracefully.',
    '',
    '  EXAMPLE (a counter, note: NO <style>, plain markup + a utility class):',
    '  { "tool": "create_live_artifact", "params": { "title": "Counter",',
    '    "html": "<div class=\\"lm-row\\"><b res=\\"n\\"></b><button class=\\"inc lm-primary\\">+1</button></div>",',
    '    "js": "R.add(\'n\', 0); root.querySelector(\'.inc\').addEventListener(\'click\', () => { R.n = R.n + 1; });" } }',
    '',
    '  UPDATING A LIVE MODULE you already made: when the user says "now add…",',
    '  "change it so…", "make it also…", call edit_artifact (NOT a fresh',
    '  create_live_artifact) with the module\'s artifactId from the catalog. A live',
    '  module is edited via the SAME html/js fields, not a single "content" blob:',
    '  { "tool": "edit_artifact", "params": { "artifactId": "art_…",',
    '    "js": "the COMPLETE new module script",',
    '    "html": "(optional) the new markup; omit to keep the current markup",',
    '    "libs": ["chartjs"]   // OPTIONAL, omit to keep the current libs',
    '  } }',
    '  • Pass a field to replace it; OMIT a field to keep it unchanged (e.g. send',
    '    only "js" to rewire behavior while keeping the markup).',
    '  • For a small tweak to a big module, use targeted edits instead; they apply',
    '    to whichever of html/js the "find" matches:',
    '    { "tool": "edit_artifact", "params": { "artifactId": "art_…",',
    '      "replacements": [ { "find": "exact snippet", "replace": "new snippet" } ] } }',
    '  • NEVER pass "content" with an embedded <script> tag: live modules do not',
    '    run a <script>; the js runs scoped to (root, R, Chart) as described above.',
    '    A content blob will render as a blank module.',
    '',
    '  After it succeeds, briefly tell the user the interactive module is shown',
    '  inline; do NOT paste the code back.',
    '',
    '  A widget that should stay current on its own (a price, a feed, a status)',
    '  can be refreshed by a recurring background run; see the widget-data',
    '  tools (schedule_artifact_updates) after building it.',
  ].join('\n');

  static ARTIFACT_DATA = [
    'WIDGET DATA TOOLS (live modules):',
    'A live module\'s saved data (its injected `store`) is a per-widget JSON',
    'object. These tools read/write the SAME object the widget\'s UI displays:',
    'when you write it, the widget re-renders instantly, no edit needed.',
    '',
    '- get_artifact_data: Read a widget\'s saved data.',
    '  { "tool": "get_artifact_data", "params": { "artifactId": "art_…" } }',
    '',
    '- update_artifact_data: Change some keys (pass ONLY the keys to change;',
    '  other keys are kept). Values must be JSON.',
    '  { "tool": "update_artifact_data", "params": { "artifactId": "art_…",',
    '    "set": { "price": 43210.5, "checkedAt": "2026-07-10 14:00" },',
    '    "remove": ["staleKey"]   // OPTIONAL',
    '  } }',
    '  On a quota error, store less (fewer/smaller values), then retry.',
    '',
    '- schedule_artifact_updates: Make a widget refresh ITSELF on a schedule:',
    '  a background agent run executes your prompt every N minutes and should',
    '  end by writing the results with update_artifact_data. Use when the user',
    '  wants a widget that stays current (a price ticker, a news box, a feed).',
    '  { "tool": "schedule_artifact_updates", "params": { "artifactId": "art_…",',
    '    "prompt": "Fetch the current BTC price from the web and update the',
    '    widget\'s data: set price (number) and checkedAt (ISO time).",',
    '    "everyMinutes": 30, "title": "BTC price refresh" } }',
    '  • Write the prompt for a FUTURE run with no context: name the data keys',
    '    the widget reads and exactly where to get the values.',
    `  • everyMinutes: ${ScheduleBounds.rangeText()}. After it succeeds, tell the user the schedule`,
    '    is active and can be managed from the Dashboard tab.',
  ].join('\n');
}

module.exports = ArtifactManuals;
