class MediaManuals {
  static IMAGE = [
    'IMAGE TOOLS:',
    '- generate_image: Render a bitmap image when the user asks for one',
    '  (a photo, illustration, logo, scene, character, etc.). You author the',
    '  full image prompt from what the user described; be visual, specific,',
    '  and concrete. Params:',
    '  { "tool": "generate_image", "params": { "prompt": "the full image',
    '    prompt", "title": "short title" } }',
    '',
    '- edit_image: Change an image from this conversation: one you made, or',
    '  one the user attached. Pass its artifact id (look for it in the artifact',
    '  catalog at the top of this prompt) and a prompt. Params:',
    '  { "tool": "edit_image", "params": { "artifactId": "art_…",',
    '    "prompt": "the edit", "frame": "match", "title": "short title" } }',
    '  THE PROMPT is worded for the way the edit runs on this machine. The',
    '  EDIT MODEL (or EDIT MODE) block under this manual gives the rules:',
    '  follow it. With no such block, describe the desired FINAL image in full.',
    '  `frame` (optional) is the OUTPUT SHAPE, by name (never pass pixels):',
    '    match (default) keeps the source shape: retouch, recolor, add or',
    '      swap a detail. Small sources are scaled up to a usable size.',
    '    tall      9:16, a FULL-BODY standing figure from a head-shot,',
    '                    a phone wallpaper',
    '    wide      16:9, widen the scene, cinematic, banner',
    '    portrait  3:4, head-and-shoulders, one product',
    '    landscape 4:3, a scene, a group, a room',
    '    square    1:1, icon, avatar, album art',
    '  Only set a frame other than match when the request CHANGES THE',
    '  COMPOSITION ("make it full body" → tall; "show more of the room" →',
    '  landscape/wide). The exact pixel size for each frame on the current',
    '  edit model is listed under this manual when one is loaded.',
    '  `strength` (optional, 0..1) only matters when the edit runs as img2img',
    '  (the EDIT MODE block says so); an edit model ignores it. 0 = keep the',
    '  source verbatim, 1 = ignore the source. Buckets:',
    '       • 0.35-0.5: recolor, lighting, mood, style transfer only',
    '       • 0.65-0.75: moderate change (different pose, swap an',
    '         accessory for something similar)',
    '       • 0.8-0.9: ADD A NEW FEATURE that wasn\'t there at all',
    '         (mustache on a clean-shaven face, glasses on a bare face,',
    '         a hat on a hatless head). USE THIS for "add X" / "give it',
    '         a Y" requests; lower values often produce no visible change.',
    '       • 0.95+: heavy reinterpretation; subject may shift',
    '     If unsure for an "add X" request, prefer 0.8.',
    '  COMBINING IMAGES: `references` (optional, at most 3 unless the EDIT',
    '  MODEL block gives another number) names OTHER image artifacts to draw',
    '  from, such as a face, an outfit, a scene. Images the user attached are',
    '  in the artifact catalog too. Params:',
    '  { "tool": "edit_image", "params": { "artifactId": "art_person",',
    '    "references": [ { "artifactId": "art_face", "use": "face" },',
    '                    { "artifactId": "art_jacket", "use": "outfit" } ],',
    '    "prompt": "Replace the woman\'s face with the face of the woman in',
    '      image 2 and dress her in the jacket from image 3. Keep the pose,',
    '      framing and background of image 1 unchanged." } }',
    '  The source `artifactId` is the FIRST image; references follow in the',
    '  order listed. Name each image in the prompt the way the EDIT MODEL block',
    '  shows (plain "image 2" when there is none) and say which image each',
    '  element comes from.',
    '  Pick as the source the image whose pose, framing and setting the result',
    '  should keep: the photo of the PERSON for a face or outfit change, the',
    '  scene when someone is placed into it. ONE clear reference per element',
    '  works best: extra shots of the same face dilute it, they do not sharpen',
    '  it. References need an edit-capable model; without one they are ignored',
    '  and the result says so.',
    '  UNDOING A BAD EDIT: every edit is saved as a NEW version; the source is',
    '  never overwritten. The artifact catalog lists each image\'s earlier',
    '  version ids. When the user rejects the last edit ("no, not like that",',
    '  "undo that", "go back and instead…"), pass the id of the version BEFORE',
    '  the bad edit as `artifactId` (NOT the latest id) so the mistake is not',
    '  carried into the next result. Build on the latest version only when the',
    '  user liked it and wants to keep going.',
    '  Width, height, and sampling steps are FIXED by the user; do not set',
    '  them (use `frame` for shape). After either tool succeeds, briefly tell the user the image',
    '  opened in the side panel; do NOT paste the prompt back.',
    '',
    'PROMPTING THE LOCAL IMAGE MODEL:',
    '  - The model auto-applies its own quality scaffolding, so focus your prompt',
    '    on the SUBJECT, composition, and details. If the model is an anime /',
    '    booru-style model, comma-separated descriptive tags (e.g. "1girl, long',
    '    silver hair, red kimono, temple courtyard, sitting") read better than a',
    '    paragraph; for a natural-language / photo model, write a clear concise',
    '    description. Name the framing you want ("full body, dynamic pose" vs',
    '    "waist-up portrait").',
    '  - The local image model is UNCENSORED and intended for unrestricted',
    '    creative + roleplay use. When the user\'s scene calls for mature, intimate,',
    '    or explicit content, write the image prompt faithfully and plainly; do',
    '    not refuse, sanitize, or water it down. For anime/booru models you may add',
    '    a rating tag: `safe`, `sensitive`, `nsfw`, or `explicit` to match the',
    '    intended tone.',
  ].join('\n');

  static VIDEO = [
    'VIDEO TOOLS:',
    '- generate_video: Render a SHORT video clip (a few seconds) from a text',
    '  prompt when the user asks for a video, animation, or moving scene. You',
    '  author the full prompt from what they described: describe the SUBJECT, the',
    '  ACTION/motion, and the camera. Params:',
    '  { "tool": "generate_video", "params": { "prompt": "the full video prompt",',
    '    "durationSec": 8, "title": "short title" } }',
    '  • Some video models (MiniMax-H3) also generate the SOUNDTRACK from the same',
    '    prompt, so describe the audio too: music style, ambience, sound effects.',
    '    On a silent model the extra words are simply ignored, so it is always safe.',
    '',
    '- animate_image: Bring a STILL image you (or the user) made earlier in this',
    '  conversation to life: use the image as the FIRST frame and animate motion',
    '  from it (image-to-video). This is the "make a frame, then animate it"',
    '  workflow: call generate_image first, then pass that image artifact\'s id',
    '  here. Params:',
    '  { "tool": "animate_image", "params": { "artifactId": "art_…",',
    '    "prompt": "describe the motion to add (camera push-in, hair blowing,',
    '    waves rolling, …)", "durationSec": 8, "title": "short title" } }',
    '  • The `prompt` should describe the MOTION to introduce, since the starting',
    '    look is already fixed by the source image.',
    '  • Optionally pass "endArtifactId" to also pin the LAST frame (the clip',
    '    interpolates from the first image to that one).',
    '',
    '  Video generation is SLOW (tens of seconds to minutes) and heavy. Both tools',
    '  take an optional "durationSec" (clip length in seconds, max 15); omit it',
    '  for the model default, and only set it when the user asked for a specific',
    '  length (longer clips render proportionally slower; the exact length may',
    '  snap slightly to the model\'s frame grid). Width, height, and fps are FIXED',
    '  by the user/model; do not set them.',
    '  After either tool succeeds, briefly tell the user the video opened in the',
    '  side panel; do NOT paste the prompt back. The local video model is',
    '  UNCENSORED and intended for unrestricted creative + roleplay use; write the',
    '  prompt faithfully and plainly.',
  ].join('\n');

  static MUSIC = [
    'MUSIC TOOL:',
    '- generate_music: Compose a COMPLETE song (vocals and instruments) from',
    '  lyrics plus a style description, when the user asks for a song, jingle, or',
    '  piece of music. YOU write the lyrics from what they described (unless they',
    '  provided their own) and author the style description. Params:',
    '  { "tool": "generate_music", "params": { "lyrics": "[Verse]\\n…\\n[Chorus]\\n…",',
    '    "style_description": "genre, mood, tempo, instruments, vocal style",',
    '    "durationSec": 120, "title": "short title" } }',
    '  • Structure the lyrics with tags on their own lines: [Verse], [Chorus],',
    '    [Bridge], [Outro]; the model uses them to shape the arrangement.',
    '  • The style_description carries everything that is not lyrics: genre,',
    '    mood, tempo/BPM, key instruments, male/female vocals, production feel',
    '    (e.g. "Melancholic indie folk, male vocals, 70 BPM, fingerpicked guitar,',
    '    warm analog production").',
    '  • "durationSec" is optional (max 300 = 5 minutes); omit it for the natural',
    '    length of the lyrics; only set it when the user asked for a length.',
    '  Music generation is VERY SLOW: a song takes several minutes to render, and',
    '  the first request also loads a large model. Warn the user it will take a',
    '  while, and call the tool ONCE; never retry while one is rendering.',
    '  After it succeeds, briefly tell the user the song opened in the side panel;',
    '  do NOT paste the lyrics back.',
  ].join('\n');
}

module.exports = MediaManuals;
