class UtilityManuals {
  static WEB = [
    'WEB TOOL:',
    '- web_search: Look something up on the live web, or read a specific page,',
    '  WITHOUT opening a browser tab. Use it for current events, facts you are',
    '  unsure about, documentation, prices, or anything past your training cutoff.',
    '  TWO modes (pass exactly one):',
    '  • SEARCH: get a ranked list of result snippets:',
    '    { "tool": "web_search", "params": { "query": "what to look up" } }',
    '  • FETCH: read the full text of ONE page (returned as clean Markdown).',
    '    After a search, pass the RESULT NUMBER as the url; do NOT retype URLs',
    '    (retyped URLs get mangled and the fetch fails):',
    '    { "tool": "web_search", "params": { "url": "2" } }        ← reads result 2',
    '    A full URL works too (for links from the user or inside a page):',
    '    { "tool": "web_search", "params": { "url": "https://example.com/article" } }',
    '    Add "find" to jump straight to a fact on a long page; it returns the',
    '    text AROUND each match instead of the top of the page:',
    '    { "tool": "web_search", "params": { "url": "2", "find": "30-year" } }',
    '',
    '  TYPICAL FLOW: search first, then fetch the most relevant result by NUMBER',
    '  (plus "find" when hunting a specific number/fact). Search results are only',
    '  short snippets AND MAY BE FROM OLD PAGES: for time-sensitive facts (prices,',
    '  rates, news), fetch the page and check its date instead of quoting snippet',
    '  figures.',
    '  • HTML pages are loaded in the real browser (JavaScript runs, ads blocked),',
    '    so you get dynamically-rendered content (live prices, rates, SPA data).',
    '  • CRITICAL: never invent or tweak a URL path. If a fetch fails, run another',
    '    web_search query and fetch a result by its number.',
    '  • Only http(s) URLs work; private/loopback addresses are blocked for safety.',
    '  • Long pages come in PARTS: each reply ends with "Part 1 of 4 ..." and the',
    '    exact call for the next part, e.g. { "url": "2", "part": 2 }. Prefer',
    '    "find" when you only need one fact; its excerpts name the part they sit in.',
    '  • For tasks that need to CLICK, fill forms, log in, or screenshot, use the',
    '    browser tools instead; web_search only READS.',
  ].join('\n');

  static KNOWLEDGE_BASE = [
    'KNOWLEDGE BASE TOOL:',
    '- search_knowledge_base: Search the user\'s own uploaded documents (PDFs,',
    '  notes, pages they added to this app\'s knowledge base) for passages relevant',
    '  to their question. Use it FIRST whenever the user asks about "my docs", a',
    '  file they uploaded, or something specific that is likely in their material',
    '  rather than general knowledge. Params:',
    '  { "tool": "search_knowledge_base", "params": { "query": "what to look for" } }',
    '',
    '  • It returns the most relevant passages as <chunk id="N" source="file"',
    '    page="P"> blocks. Base your answer on those passages and refer to the',
    '    source file/page when it helps; do not invent content that is not in them.',
    '  • If it returns no passages, tell the user their documents don\'t cover it',
    '    (or answer from general knowledge, making clear it is not from their docs).',
    '  • Don\'t search the same thing repeatedly; one good query is usually enough.',
  ].join('\n');

  static VALIDATE = [
    'CODE VALIDATION:',
    '- validate_code: Run a fast in-process linter / parser over a code snippet',
    '  and get back any errors or warnings WITH line numbers: a second pair of',
    '  eyes before you tell the user the code is finished. Params:',
    '  { "tool": "validate_code", "params": { "language": "typescript",',
    '    "code": "the COMPLETE source as one string",',
    '    "filename": "(optional, e.g. deploy.ts, used to infer language)" } }',
    '',
    '  Supported: JavaScript/JSX, TypeScript/TSX, JSON/JSONC (errors + warnings),',
    '  and PowerShell (syntax errors only: unbalanced braces, unterminated',
    '  strings, malformed params; no style/security rules). Other languages',
    '  return "not available" (that is a skip, not a failure; proceed normally).',
    '',
    '  WHEN TO USE: after you write or revise non-trivial code in a SUPPORTED',
    '  language and before you claim it works. If it reports errors, fix them',
    '  and re-validate until clean, THEN answer.',
    '',
    '  NOTE: create_artifact and edit_artifact already AUTO-VALIDATE code',
    '  artifacts and return any diagnostics in their result; read those and',
    '  fix issues with edit_artifact before telling the user you are done. Use',
    '  validate_code for code you are NOT putting in an artifact.',
  ].join('\n');

  static PROGRAMMATIC = [
    'PROGRAMMATIC TOOL:',
    '- send_webhook: Deliver data to an automation endpoint by HTTP: the way to',
    '  SEND a result somewhere (a webhook, Home Assistant, n8n, Zapier, a local',
    '  server) rather than show it to the user. Params:',
    '  { "tool": "send_webhook", "params": { "url": "https://example.com/hook",',
    '    "payload": { "any": "JSON object: the data to deliver" },',
    '    "method": "(optional) POST | PUT | PATCH, default POST",',
    '    "headers": { "(optional) extra headers, e.g. an API key": "..." } } }',
    '',
    '  • ONLY call endpoints the user gave you (in this conversation or the task',
    '    instructions). Never invent, guess, or reuse an endpoint from elsewhere.',
    '  • Put the actual data in "payload" as a sensible JSON object; a plain',
    '    string payload is sent as raw text for text-style hooks.',
    '  • The result includes the HTTP status and the first part of the response',
    '    body; report delivery (or the exact failure) in your answer.',
    '  • One delivery per call; do not retry a 4xx (fix the request instead).',
  ].join('\n');
}

module.exports = UtilityManuals;
