import ChatIcons from '../ChatIcons.js';

export default class ComposerView {
  static MAX_TEXTAREA_PX = 220;

  static NO_MODEL = 'No model is set up yet. Open Setup to pick a local model or add a provider.';

  static SEND_TITLE = 'Send (Enter). Shift+Enter for a new line';

  constructor(ctx) {
    this._ctx = ctx;
  }

  static html(big) {
    return ''
      + '<div class="cm-composer-wrap">'
      + '  <div class="cm-nomodel luma-callout warn" data-cm-nomodel role="status" hidden>'
      + '    <span class="cm-nomodel-text">' + ComposerView.NO_MODEL + '</span>'
      + '    <button class="luma-btn luma-btn--sm" type="button" data-cm-open-setup>Open Setup</button>'
      + '  </div>'
      + '  <div class="cm-attachments" data-cm-attachments hidden></div>'
      + '  <div class="cm-composer">'
      + '    <textarea rows="1" placeholder="' + (big ? 'How can I help you today? Type / for commands' : 'Reply...') + '"></textarea>'
      + '    <div class="cm-composer-row">'
      + '      <div class="cm-composer-left">'
      + '        <button class="cm-gear" type="button" title="Chat options: model, tools, attachments">' + ChatIcons.gear + '</button>'
      + '        <button class="cm-tabs-btn" type="button" title="Ask about an open tab" hidden>' + ChatIcons.globe + '</button>'
      + '        <span class="cm-effort" data-cm-effort hidden></span>'
      + '        <button class="cm-mic" type="button" title="Voice conversation">' + ChatIcons.mic + '</button>'
      + '      </div>'
      + '      <div class="cm-composer-right">'
      + '        <span class="cm-usage" title="Tokens used by the last turn"></span>'
      + '        <button class="cm-send" title="' + ComposerView.SEND_TITLE + '" disabled>' + ChatIcons.send + '</button>'
      + '      </div>'
      + '    </div>'
      + '  </div>'
      + (big ? '' : '<div class="cm-disclaimer">Responses are generated by an AI model and may be inaccurate - double-check anything important.</div>')
      + '</div>';
  }

  wire(scope) {
    this._wireTextarea(scope.querySelector('.cm-composer textarea'));
    this._wireSend(scope);
    this._ctx.thinkPill.render();
    this._wireGear(scope.querySelector('.cm-gear'));
    this._ctx.tabs.wireButton(scope.querySelector('.cm-tabs-btn'));
    this._wireMic(scope.querySelector('.cm-mic'));
    this._wireOpenSetup(scope.querySelector('[data-cm-open-setup]'));
    this._ctx.usage.render();
    this._ctx.attachments.render();
    this._ctx.availability.render();
  }

  setSendStop(streaming) {
    this._ctx.root.querySelectorAll('.cm-send').forEach((b) => {
      b.classList.toggle('cm-stop', streaming);
      b.innerHTML = streaming ? ChatIcons.stop : ChatIcons.send;
      b.title = streaming ? 'Stop (Esc)' : ComposerView.SEND_TITLE;
    });
    this.refreshSendState();
  }

  refreshSendState() {
    const { state, root } = this._ctx;
    root.querySelectorAll('.cm-composer').forEach((c) => {
      const send = c.querySelector('.cm-send');
      if (!send) return;
      const ta = c.querySelector('textarea');
      send.disabled = state.streaming
        ? !state.streamOnScreen()
        : (!state.aiAvailable || (!(ta && ta.value.trim()) && state.attachments.length === 0));
    });
  }

  focus() {
    const ta = this._ctx.root.querySelector('.cm-composer textarea');
    if (ta) ta.focus();
  }

  clearReplyBox() {
    const ta = this._ctx.els.composerBar.querySelector('.cm-composer textarea');
    if (ta) { ta.value = ''; ta.style.height = 'auto'; }
  }

  _wireTextarea(ta) {
    if (!ta) return;
    const grow = () => { ta.style.height = 'auto'; ta.style.height = Math.min(ta.scrollHeight, ComposerView.MAX_TEXTAREA_PX) + 'px'; };
    ta.addEventListener('input', () => { grow(); this.refreshSendState(); });
    ta.addEventListener('paste', (e) => this._ctx.paste.onPaste(e));
    this._ctx.commands.wire(ta);
    ta.addEventListener('keydown', (e) => {
      if (this._ctx.commands.onKey(e, ta)) return;
      if (this._ctx.shortcuts.onComposerKey(e, ta)) return;
      if (e.key !== 'Enter' || e.shiftKey) return;
      e.preventDefault();
      if (this._ctx.state.streaming) return;
      this._ctx.sender.submit(ta.value);
    });
    setTimeout(() => ta.focus(), 0);
  }

  _wireSend(scope) {
    const send = scope.querySelector('.cm-send');
    const ta = scope.querySelector('.cm-composer textarea');
    if (!send) return;
    send.addEventListener('click', () => {
      const { state, sender } = this._ctx;
      if (state.streaming) { if (state.streamOnScreen()) sender.abort(); return; }
      if (ta) sender.submit(ta.value);
    });
  }

  _wireGear(btn) {
    if (!btn) return;
    btn.addEventListener('click', (e) => { e.stopPropagation(); this._ctx.gear.toggle(btn); });
  }

  _wireMic(btn) {
    if (!btn) return;
    const v = this._ctx.voice.ensure();
    if (v) v.wireButton(btn);
    else btn.hidden = true;
  }

  openSetup() {
    this._ctx.switchToSetup();
    const nav = this._ctx.collaborators.setupNav;
    if (nav) { try { nav.go('settings'); } catch (_) {} }
  }

  _wireOpenSetup(btn) {
    if (btn) btn.addEventListener('click', () => this.openSetup());
  }
}
