const CompletionKind = require('./extension-autocomplete/CompletionKind');

class ExtensionAutocompleteData {
  static CONTEXT_PROPERTIES = [
    {
      label: 'extensionId',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'The unique ID of this extension (e.g. "ai-chat").',
    },
    {
      label: 'llmCatalog',
      kind: CompletionKind.FIELD,
      detail: 'LlmCatalogAccess',
      documentation: [
        'Contribute LLM inference runtimes and downloadable add-on models.',
        '',
        'Methods:',
        '  registerRuntime(entry, hooks?) - runtime row + optional { detect, install, uninstall, planLaunch }',
        '    (a github-release row with repo + assetPatterns needs no hooks; nativeQuantPattern claims quants)',
        '  unregisterRuntime(id)',
        '  listRuntimes()',
        '  registerModel(entry)         - add-on model with file {url, filename, sha256} + requiresRuntime',
        '  unregisterModel(id)',
        '  listModels()',
        '',
        'Entries auto-unregister when the extension deactivates.',
      ].join('\n'),
    },
    {
      label: 'extensionDir',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'Absolute filesystem path to this extension\'s directory.',
    },
    {
      label: 'ipc',
      kind: CompletionKind.FIELD,
      detail: 'ScopedIPCBridge',
      documentation: [
        'Auto-namespaced IPC bridge (namespace: ext.{extensionId}).',
        '',
        'Methods:',
        '  handle(channel, handler)  - register invoke-style handler',
        '  on(channel, handler)      - register event-style listener',
        '  removeHandle(channel)     - remove a handler',
        '  removeOn(channel)         - remove a listener',
        '  send(window, channel, data) - send event to renderer',
      ].join('\n'),
    },
    {
      label: 'db',
      kind: CompletionKind.FIELD,
      detail: 'DatabaseService',
      documentation: [
        'Namespaced key-value + SQL database (auto-prefixed to ext.{extensionId}.*).',
        'Only available if core:database is declared in dependencies.',
        '',
        'Methods:',
        '  get(key, defaultValue)           - get a setting value',
        '  set(key, value)                  - set a setting value',
        '  delete(key)                      - delete a setting',
        '  getAll(prefix)                   - get all settings under a prefix',
        '  query(sql, ...params)            - run a read SQL query',
        '  run(sql, ...params)              - run a write SQL statement',
        '  hasTableAccess(tableName)         - check table access',
        '  getNamespace()                    - get the namespace prefix',
      ].join('\n'),
    },
    {
      label: 'browser',
      kind: CompletionKind.FIELD,
      detail: 'BrowserService',
      documentation: [
        'Browser automation service. Only available if core:browser is declared.',
        '',
        'Methods:',
        '  getTabs()                      - get all open tabs',
        '  createTab(url, options)        - create a new tab',
        '  closeTab(tabId)                - close a tab',
        '  navigate(tabId, url)           - navigate tab to URL',
        '  refresh(tabId)                 - refresh a tab',
        '  getSource(tabId, options)      - get page HTML source',
        '  screenshot(tabId, options)     - take a screenshot',
        '  click(tabId, options)          - click an element',
        '  fill(tabId, options)           - fill a form field',
        '  waitFor(tabId, options)        - wait for element/condition',
        '  scroll(tabId, options)         - scroll in a tab',
        '  pressKey(tabId, options)       - press a key',
        '  getElement(tabId, options)     - get element info',
        '  getTable(tabId, options)       - extract table data',
        '  executeJs(tabId, code)         - execute JavaScript',
        '  getConsoleLogs(tabId, options) - get console output',
        '  handleDialog(tabId, options)   - handle JS dialog',
        '  extractData(tabId, options)    - extract structured data',
        '  attachCDP(extensionId, fn)     - attach CDP listener',
        '  registerWebviewPreload(id, path) - register preload script',
        '  onTabNavigated(callback)       - listen for tab navigation',
        '  onTabCreated(callback)         - listen for tab creation',
        '  onTabClosed(callback)          - listen for tab close',
        '  onWebviewAttached(callback)    - listen for webview attach',
      ].join('\n'),
    },
    {
      label: 'llm',
      kind: CompletionKind.FIELD,
      detail: 'LLMService',
      documentation: [
        'LLM routing service. Only available if core:llm-service is declared.',
        '',
        'Methods:',
        '  registerSlot(slotId, config)    - register an LLM slot',
        '  unregisterSlot(slotId)          - unregister a slot',
        '  getSlotConfig(slotId)           - get config for a slot',
        '  setSlotConfig(slotId, provider, model) - set slot config',
        '  clearSlotConfig(slotId)         - clear slot config',
        '  getAllSlots()                   - get all registered slots',
        '  sendCompletion(slotId, messages, options) - send LLM request',
        '  createStream(slotId, messages, options, handlers) - streaming',
        '  getProvider(key)                - get a provider by key',
        '  getProviders()                  - get all providers',
        '  getAllAvailableModels()         - get all available models',
        '  getActiveProviderKey()          - get active provider key',
        '  getActiveProvider()             - get active provider instance',
      ].join('\n'),
    },
    {
      label: 'sharedServices',
      kind: CompletionKind.FIELD,
      detail: 'object',
      documentation: [
        'Map of all core services (browser, llm, database, etc.).',
        'Access any core service regardless of dependency declaration.',
      ].join('\n'),
    },
    {
      label: 'logger',
      kind: CompletionKind.FIELD,
      detail: 'ActivityLogger',
      documentation: [
        'Caller-bound activity logger. Auto-registers this extension as a caller.',
        '',
        'Methods:',
        '  isEnabled()    - check if logging is enabled for this caller',
        '  log(action, data) - log an action',
        '  span({ action, summary, ... }, fn) - wrap async work in a span',
      ].join('\n'),
    },
    {
      label: 'extensions',
      kind: CompletionKind.FIELD,
      detail: 'object',
      documentation: [
        'Public APIs from loaded extension dependencies.',
        'Keys are extension IDs (e.g. context.extensions["ai-chat"]).',
      ].join('\n'),
    },
    {
      label: 'events',
      kind: CompletionKind.FIELD,
      detail: 'EventBus',
      documentation: [
        'Simple pub/sub event bus scoped to this extension.',
        '',
        'Methods:',
        '  on(event, callback)   - subscribe to an event',
        '  emit(event, data)     - emit an event',
        '  off(event, callback)  - unsubscribe',
      ].join('\n'),
    },
    {
      label: 'expose',
      kind: CompletionKind.METHOD,
      detail: 'expose(name, fn, options)',
      documentation: [
        'Register a function as a REST endpoint, MCP tool, or both.',
        '',
        'Parameters:',
        '  name        - function name (used as route path and MCP tool suffix)',
        '  fn          - async (args) => result',
        '  options     - {',
        '    targets: ["api", "mcp"]  - where to expose',
        '    description: string      - human-readable description',
        '    method: "post"           - HTTP method for REST',
        '    params: object           - parameter definitions',
        '  }',
        '',
        'Example:',
        '  context.expose("getData", async ({ id }) => {',
        '    return { id, value: "hello" };',
        '  }, {',
        '    description: "Get data by ID",',
        '    params: { id: { type: "string", required: true } }',
        '  });',
      ].join('\n'),
    },
  ];

  static DEPENDENCY_SHORTCUT_INFO = {
    label: 'context shortcut',
    documentation: [
      'Extension dependencies are also available as direct context properties.',
      'e.g. if "ext:ai-chat" is a dependency:',
      '  context.aiChat  →  context.extensions["ai-chat"]',
      '',
      'Note: reserved names (extensionId, ipc, db, browser, etc.) are NOT shortcut.',
    ].join('\n'),
  };

  static MANIFEST_FIELDS = [
    {
      label: 'id',
      kind: CompletionKind.FIELD,
      detail: 'string (required)',
      documentation: 'Unique kebab-case identifier (e.g. "my-extension").',
    },
    {
      label: 'name',
      kind: CompletionKind.FIELD,
      detail: 'string (required)',
      documentation: 'Display name (e.g. "My Extension").',
    },
    {
      label: 'version',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'Semver version (e.g. "1.0.0").',
    },
    {
      label: 'description',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'Short description of what the extension does.',
    },
    {
      label: 'loadPriority',
      kind: CompletionKind.FIELD,
      detail: 'number',
      documentation: 'Load order priority (lower = earlier). Default: 100.',
    },
    {
      label: 'private',
      kind: CompletionKind.FIELD,
      detail: 'boolean',
      documentation: 'If true, extension cannot be exported. Default: false.',
    },
    {
      label: 'debugOnly',
      kind: CompletionKind.FIELD,
      detail: 'boolean',
      documentation: 'If true, extension is skipped in production/Docker builds.',
    },
    {
      label: 'dependencies',
      kind: CompletionKind.FIELD,
      detail: 'object',
      documentation: [
        'Dependency declarations.',
        '',
        '  required: {',
        '    "core:browser": { reason: "..." },',
        '    "core:database": { tables: [{ name: "my_table" }] },',
        '    "core:llm-service": {',
        '      slots: [{ id: "mySlot", label: "...", required: true }]',
        '    },',
        '    "ext:other-ext": { reason: "..." },',
        '  },',
        '  optional: { ... }',
      ].join('\n'),
    },
    {
      label: 'ui',
      kind: CompletionKind.FIELD,
      detail: 'object',
      documentation: [
        'UI slot registrations.',
        '',
        '  "settings-tab": { label: "...", tabId: "..." },',
        '  "right-sidebar": { label: "..." },',
        '  "toolbar-button": { label: "...", tooltip: "..." },',
        '  "toolbar-buttons-right": { label: "..." },',
        '  "bottom-bar": { label: "..." },',
      ].join('\n'),
    },
    {
      label: 'main',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'Path to main process entry point (e.g. "./main.js").',
    },
    {
      label: 'renderer',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'Path to renderer process entry point (e.g. "./renderer.js").',
    },
    {
      label: 'routes',
      kind: CompletionKind.FIELD,
      detail: 'string | object',
      documentation: [
        'REST API routes.',
        'String: "./routes.js" (auto-prefix /api/ext/{id}/)',
        'Object: { file: "./routes.js", prefix: "/api/custom" }',
      ].join('\n'),
    },
    {
      label: 'mcpTools',
      kind: CompletionKind.FIELD,
      detail: 'string | object',
      documentation: [
        'MCP tool definitions.',
        'String: "./mcp-tools.js"',
        'Object: { file: "./mcp-tools.js" }',
      ].join('\n'),
    },
    {
      label: 'navigationBar',
      kind: CompletionKind.FIELD,
      detail: 'object',
      documentation: [
        'Declarative nav bar button + panel.',
        '',
        '  {',
        '    label: "My Panel",',
        '    tooltip: "Toggle panel",',
        '    icon: "flask",',
        '    panel: {',
        '      location: "right-panel" | "bottom-bar",',
        '      htmlFile: "./panel.html",',
        '    }',
        '  }',
      ].join('\n'),
    },
    {
      label: 'settings',
      kind: CompletionKind.FIELD,
      detail: 'object',
      documentation: [
        'Declarative settings tab.',
        '',
        '  {',
        '    label: "My Settings",',
        '    tabId: "my-settings",',
        '    htmlFile: "./settings.html",',
        '  }',
      ].join('\n'),
    },
    {
      label: 'extensionsAction',
      kind: CompletionKind.FIELD,
      detail: 'object',
      documentation: [
        'A button this extension contributes to the Extensions management area.',
        'Core renders it generically, optionally collects a brief, then launches',
        'a chat mode via a one-shot intent (the chat mode owns the behaviour).',
        '',
        '  {',
        '    label: "✨ Vibe",',
        '    variant: "primary" | "secondary",',
        '    gate: "llm",                 // only show when an LLM is configured',
        '    modeIntent: "code",          // chat mode launched on click',
        '    prompt: {                    // optional modal → intent data',
        '      title: "...", subtitle: "...", submitLabel: "Start",',
        '      fields: [{ key, label, type: "text" | "textarea", required, placeholder }],',
        '    },',
        '  }',
      ].join('\n'),
    },
    {
      label: 'extensionsActions',
      kind: CompletionKind.FIELD,
      detail: 'array',
      documentation: [
        'Multiple Extensions-area buttons (the plural of extensionsAction). Same',
        'shape per entry; core renders one button each, gated independently. Use',
        'this when one extension contributes several launchers (e.g. code-mode\'s',
        '"Vibe" + "Code a project").',
        '',
        '  extensionsActions: [',
        '    { label: "✨ Vibe", gate: "llm", modeIntent: "code", prompt: { ... } },',
        '    { label: "Code a project", gate: "llm", modeIntent: "code", prompt: { ... } },',
        '  ]',
      ].join('\n'),
    },
  ];

  static CSS_CLASSES = [
    { label: 'ext-panel', detail: 'Main panel container' },
    { label: 'ext-card', detail: 'Card container' },
    { label: 'ext-card-header', detail: 'Card header' },
    { label: 'ext-card-body', detail: 'Card body' },
    { label: 'ext-form-grid', detail: 'Form grid layout' },
    { label: 'ext-layout-inline', detail: 'Inline flex layout' },
    { label: 'ext-layout-inline--gap-sm', detail: 'Inline with small gap' },
    { label: 'ext-layout-spacer', detail: 'Flex spacer' },
    { label: 'luma-field', detail: 'Form field group' },
    { label: 'luma-field-label', detail: 'Form label' },
    { label: 'luma-field-input', detail: 'Text input' },
    { label: 'luma-field-select', detail: 'Select dropdown' },
    { label: 'luma-field-help', detail: 'Help text under field' },
    { label: 'luma-form-actions', detail: 'Button row' },
    { label: 'ext-form-buttons--start', detail: 'Button row (left-aligned)' },
    { label: 'luma-btn', detail: 'Base button' },
    { label: 'primary', detail: 'Primary button' },
    { label: 'danger', detail: 'Danger button' },
    { label: 'luma-btn--sm', detail: 'Small button' },
    { label: 'luma-dot', detail: 'Status indicator dot' },
    { label: 'ok', detail: 'Active status dot' },
    { label: 'luma-callout', detail: 'Info callout box' },
    { label: 'luma-empty', detail: 'Empty state / empty list placeholder' },
    { label: 'luma-error', detail: 'Error message box' },
    { label: 'luma-section-label', detail: 'Section heading' },
    { label: 'ext-text-danger', detail: 'Danger text color' },
    { label: 'ext-mt-8', detail: 'Margin top 8px' },
    { label: 'ext-mt-12', detail: 'Margin top 12px' },
    { label: 'ext-mt-16', detail: 'Margin top 16px' },
    { label: 'ext-mb-8', detail: 'Margin bottom 8px' },
    { label: 'ext-mb-12', detail: 'Margin bottom 12px' },
    { label: 'ext-mb-16', detail: 'Margin bottom 16px' },
    { label: 'ext-divider', detail: 'Horizontal divider' },
    { label: 'ext-hidden', detail: 'Hide element (display: none)' },
    { label: 'ext-list-view', detail: 'Extension list container' },
    { label: 'ext-list-item', detail: 'List item row' },
    { label: 'ext-list-item--disabled', detail: 'Disabled list item' },
    { label: 'ext-list-item-info', detail: 'List item info section' },
    { label: 'ext-list-item-actions', detail: 'List item actions section' },
    { label: 'luma-badge', detail: 'Status/dependency badge (+ .ok/.bad/.warn/.muted)' },
    { label: 'ext-config-header', detail: 'Config page header' },
    { label: 'ext-config-back-btn', detail: 'Back button in config' },
    { label: 'luma-switch', detail: 'Toggle switch wrapper' },
    { label: 'luma-switch-track', detail: 'Toggle switch track/slider' },
  ];

  static RENDERER_CONTEXT = [
    {
      label: 'slotManager',
      kind: CompletionKind.FIELD,
      detail: 'UISlotManager',
      documentation: [
        'UI slot manager for registering extension UI components.',
        '',
        'Methods:',
        '  register(slotName, extId, content, config) - mount UI into a slot',
        '  activate(slotName, extId)                  - activate tab in tabbed slot',
        '  unregister(slotName, extId)                - remove UI from a slot',
        '  getContainer(slotName)                      - get DOM container',
        '  toggle(slotName)                            - toggle slot visibility',
        '  setCallback(slotName, extId, name, fn)     - attach lifecycle callback',
        '',
        'Slots: settings-tab, right-sidebar, toolbar-button,',
        '       toolbar-buttons-right, bottom-bar, right-panel',
      ].join('\n'),
    },
    {
      label: 'ipcBridge',
      kind: CompletionKind.FIELD,
      detail: 'IPCBridgeRenderer',
      documentation: [
        'Renderer-side IPC bridge for communicating with main process.',
        '',
        'Methods:',
        '  invoke(channel, ...args) - invoke a main process handler',
        '  on(channel, handler)     - listen for main process events',
        '  off(channel, handler)    - remove event listener',
        '  forExtension(extId)      - create scoped bridge for an extension',
      ].join('\n'),
    },
    {
      label: 'extensionId',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'The extension ID.',
    },
    {
      label: 'extensionDir',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'Absolute path to the extension directory.',
    },
    {
      label: 'containers',
      kind: CompletionKind.FIELD,
      detail: 'object',
      documentation: [
        'Auto-registered containers from declarative manifest fields.',
        '  { panelContainer, settingsContainer }',
      ].join('\n'),
    },
  ];

  static MCP_TOOL_FIELDS = [
    {
      label: 'name',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'Tool name (unique identifier).',
    },
    {
      label: 'description',
      kind: CompletionKind.FIELD,
      detail: 'string',
      documentation: 'Human-readable description of what the tool does.',
    },
    {
      label: 'inputSchema',
      kind: CompletionKind.FIELD,
      detail: 'JSONSchema',
      documentation: [
        'JSON Schema defining the tool\'s input parameters.',
        '',
        '  {',
        '    type: "object",',
        '    properties: {',
        '      param: { type: "string", description: "..." }',
        '    },',
        '    required: ["param"]',
        '  }',
      ].join('\n'),
    },
  ];

  static build(extensionApis) {
    return {
      contextProperties: ExtensionAutocompleteData.CONTEXT_PROPERTIES,
      manifestFields: ExtensionAutocompleteData.MANIFEST_FIELDS,
      cssClasses: ExtensionAutocompleteData.CSS_CLASSES,
      rendererContext: ExtensionAutocompleteData.RENDERER_CONTEXT,
      mcpToolFields: ExtensionAutocompleteData.MCP_TOOL_FIELDS,
      extensionApis: ExtensionAutocompleteData._extensionApiCompletions(extensionApis),
      dependencyShortcutInfo: ExtensionAutocompleteData.DEPENDENCY_SHORTCUT_INFO,
    };
  }

  static _extensionApiCompletions(extensionApis) {
    const completions = {};
    for (const [id, ext] of Object.entries(extensionApis || {})) {
      const manifest = ext.manifest || {};
      completions[id] = {
        name: manifest.name || id,
        description: manifest.description || '',
        methods: ExtensionAutocompleteData._methodCompletions(id, manifest, ext.api || {}),
      };
    }
    return completions;
  }

  static _methodCompletions(id, manifest, api) {
    return Object.entries(api).map(([methodName, member]) => ({
      label: methodName,
      kind: typeof member === 'function' ? CompletionKind.METHOD : CompletionKind.FIELD,
      detail: typeof member === 'function' ? 'function' : typeof member,
      documentation: `${manifest.name || id}.${methodName}`,
    }));
  }
}

module.exports = ExtensionAutocompleteData;
